calculadoralogin/cadastro/urls.py
from django.urls import path
from . import views

app_name = 'cadastro'

urlpatterns = [
    path('', views.Login, name = 'login'),
    path('logar', views.Logar, name = 'logar'),
    path('cadastro', views.PaginaFormCadastro, name = 'cadastro'),
    path('cadastrar', views.Cadastrar, name = 'cadastrar')
]

calculadoralogin/cadastro/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin


class UsuarioManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("O e-mail é obrigatório")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)  
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)

class Usuario(AbstractBaseUser, PermissionsMixin):
    idusuario = models.AutoField(primary_key=True)
    email = models.EmailField(unique=True)
    nome = models.CharField(max_length=255)
    dtinclusao = models.DateField(null=False, auto_now_add=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nome']  

    objects = UsuarioManager()

    def __str__(self):
        return self.email


calculadoralogin/cadastro/forms.py
from django import forms
from .models import Usuario

class FormularioCadastro(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = [
            'nome',
            'email',
            'password'
        ]

class FormularioLogin(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = [
            'email',
            'password'
        ]

calculadoralogin/cadastro/views.py
from django.shortcuts import render, redirect
from .forms import FormularioCadastro, FormularioLogin
from django.http import  Http404
from django.contrib.auth import authenticate, login
from django.urls import reverse
from django.contrib import messages


def PaginaFormCadastro(request):
    formulario_cadastro = request.session.get('formulario_cadastro', None)
    form = FormularioCadastro(formulario_cadastro)
    return render(request, 'cadastro.html', {'form': form})

#Função para cadastrar
def Cadastrar(request):
    if not request.POST:
        raise Http404()
    
    POST = request.POST
    request.session['formulario_cadastro'] = POST
    form = FormularioCadastro(POST)
    if form.is_valid():
        form.save()
        del(request.session['formulario_cadastro'])
        return redirect('cadastro:login')
    
    return redirect('cadastro:cadastro')

def Login(request):
    form = FormularioLogin()
    return render(request, 'login.html', {'form' : form, 'form_action': reverse('cadastro:logar')})

def Logar(request):
    if not request.POST:
        raise Http404()

    form = FormularioLogin(request.POST)

    if form.is_valid():
        user = authenticate(
            request,
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password']
        )

        if user is not None:
            login(request, user)
            
        else:
            messages.error(request, 'Invalid username or password')
    else:
        messages.error(request, 'Invalid username or password')
    return redirect(reverse('calculadora:calculadora'))

calculadoralogin/cadastro/templates/cadastro.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>Cadastro</title>
    <link rel="stylesheet" href="{%static 'cadastro/css/styles.css'%}">
</head>
<body>
    <h1> Cadastro </h1>
    <form action="{%url 'cadastro:cadastrar'%}" method="POST">
        {% csrf_token %}
        <div class = "form-content form-content-grid"> 
            {%for field in form%}
                <div class = "form-group">
                    <label for="{{field.id_for_label}}"> {{field.label}} </label>
                    {{field}}
                </div>
            {%endfor%}
        </div>
        <div class = "form-content form-content-grid"> 
            <div class = "form-group">
                <button type="submit"> Cadastrar </button>
            </div>
        </div>
        
            <div class = "form-content form-content-grid"> 
                <div class = "form-group">
                    <a href={%url 'cadastro:login'%}>Já tenho cadastro</a>
                </div>
            </div>
        
    </form>
</body>
</html>

calculadoralogin/cadastro/templates/login.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>Login</title>
    <link rel="stylesheet" href="{%static 'cadastro/css/styles.css'%}">
</head>
<body>
    <h1> Login </h1>
    <form action="{%url 'cadastro:logar'%}" method="POST">
        {% csrf_token %}
        <div class = "form-content form-content-grid"> 
            {%for field in form%}
                <div class = "form-group">
                    <label for="{{field.id_for_label}}"> {{field.label}} </label>
                    {{field}}
                </div>
            {%endfor%}
        </div>
        <div class = "form-content form-content-grid"> 
            <div class = "form-group">
                <button type="submit"> Login </button>
            </div>
        </div>
            <div class = "form-content form-content-grid"> 
                <div class = "form-group">
                    <a href={%url 'cadastro:cadastro'%}>Não tenho cadastro</a>
                </div>
            </div>
        
    </form>
</body>
</html>